// All UI copy lives here so an Arabic pass can be done in one file.
// Rules from the brief: no em dashes, no "AI", "Sia" never "Sia Partners".

export const strings = {
  app: {
    name: 'STRATA',
    tagline: 'Dynamic strategy cockpit',
    client: 'Saudi Lime Industries Company, 2027 to 2031',
    illustrative: 'Illustrative data',
    illustrativeLong: 'Illustrative data. Invented for this proof of concept, not SLIC actuals.',
    scenario: 'Scenario',
    reset: 'Reset to base',
    builtBy: 'A Sia proof of concept',
  },
  rail: {
    levers: 'Levers',
    presets: 'Scenario presets',
    explain: 'Explain this result',
    explainHint: 'Show the rules and assumptions behind every number.',
    moves: 'Moves',
    custom: 'Custom',
  },
  scenarios: {
    base: 'Base',
    growth: 'Growth',
    upside: 'Upside',
    downside: 'Downside',
    custom: 'Custom',
  } as Record<string, string>,
  levers: {
    L1: {
      options: { delayed: 'Delayed', onPlan: 'On plan', accelerated: 'Accelerated' },
      fine: 'Giga-project phasing',
      unit: 'x base growth',
    },
    L2: { unit: 'index, base 100' },
    L3: { unit: 'SAR m over 5 years' },
    L4: {
      options: { organic: 'Organic', selective: 'Selective', aggressive: 'Aggressive' },
      long: { organic: 'Organic only', selective: 'Selective inorganic', aggressive: 'Aggressive' },
    },
    L5: {
      options: { domestic: 'Domestic', gcc: 'GCC', extended: 'Extended' },
      long: { domestic: 'Domestic only', gcc: 'GCC', extended: 'GCC + East Africa and South Asia' },
    },
    L6: {
      options: { none: 'None', voluntary: 'Voluntary', regulated: 'Regulated' },
      unit: 'SAR per tCO2',
    },
    short: {
      L1: 'demand',
      L2: 'energy index',
      L3: 'envelope',
      L4: 'risk appetite',
      L5: 'export ambition',
      L6: 'carbon cost',
    } as Record<string, string>,
  },
  assumptionKeys: {
    demand: 'Demand',
    utilization: 'Utilization',
    priceIndex: 'Price index',
    costPerTon: 'Cost per ton',
    ebitda: 'EBITDA',
    portfolio: 'Portfolio',
    capex: 'Capex',
    roadmap: 'Roadmap',
    sites: 'Sites',
    classification: 'Classification',
  } as Record<string, string>,
  views: {
    direction: {
      tab: 'Strategic direction',
      title: 'Strategic direction',
      lead: 'Where to play, how each product market is classified, and which layers of the plan move when a lever moves.',
    },
    portfolio: {
      tab: 'Growth portfolio',
      title: 'Growth portfolio',
      lead: 'Every initiative, funded or deferred or out, with the lever value that would change its status.',
    },
    financials: {
      tab: 'Financial plan',
      title: 'Financial plan',
      lead: 'Revenue, EBITDA, capex and free cash flow for 2027 to 2031 against the base case.',
    },
    operations: {
      tab: 'Operations and people',
      title: 'Operations and people',
      lead: 'Site capacity and utilization, capex phasing, headcount and Saudization under the current scenario.',
    },
    roadmap: {
      tab: 'Roadmap',
      title: 'Roadmap',
      lead: 'Selected initiatives on a 2027 to 2031 timeline in the five plan layers, with dependencies.',
    },
    tracker: {
      tab: 'Tracker',
      title: 'Tracker',
      lead: 'Plan assumptions against actuals, and the decisions that become due when they diverge.',
    },
  },
  financials: {
    kpi: {
      revenue2031: '2031 revenue',
      margin2031: '2031 EBITDA margin',
      cumCapex: 'Cumulative capex',
      cumFcf: 'Cumulative free cash flow',
    },
    units: { sarm: 'SAR m', pct: '%', plan: '2027 to 2031' },
    vsBase: 'vs Base',
    mainChart: 'Revenue and EBITDA',
    mainChartLead: '2026 actual, then the plan. Dashed lines are the Base case.',
    secondChart: 'Capex and free cash flow',
    secondChartLead:
      'Capex stacked as base business and initiatives. Free cash flow after working capital.',
    legend: {
      revenue: 'Revenue',
      ebitda: 'EBITDA',
      baseRevenue: 'Base revenue',
      baseEbitda: 'Base EBITDA',
      capexBase: 'Base capex',
      capexInitiatives: 'Initiative capex',
      fcf: 'Free cash flow',
    },
    strip: 'Scenario compare',
    stripLead: 'The four cases the plan must hold, and where the current levers sit.',
    stripCols: {
      scenario: 'Scenario',
      revenue: 'Revenue 2031',
      ebitda: 'EBITDA 2031',
      fcf: 'Cumulative FCF',
    },
  },
  portfolio: {
    columns: { in: 'In plan', deferred: 'Deferred', out: 'Out' },
    columnLead: {
      in: 'Funded within the envelope.',
      deferred: 'Viable, waiting on capital, returns or a dependency.',
      out: 'Fails a strategic rule at these lever values.',
    },
    strip: {
      envelope: 'Capital envelope',
      committed: 'Committed',
      headroom: 'Headroom',
      counts: 'Initiatives',
      diversification: '2031 revenue from new products and markets',
    },
    card: {
      capex: 'Capex',
      npv: 'NPV',
      ebitda: 'EBITDA',
      owner: 'Owner',
      dependsOn: 'Depends on',
      start: 'Start',
    },
    reason: {
      capital: 'Envelope exhausted',
      returns: 'NPV below zero at the hurdle rate',
      dependency: 'Waits for a dependency',
    },
    trigger: {
      becomesViable: 'Becomes viable if',
      fundedOnce: 'Funded once',
      staysIn: 'Stays in while',
      dropsOut: 'Drops out if',
      more: 'more',
      noBoundary: 'No lever value changes this.',
    },
    layers: {
      quick_wins: 'Quick wins',
      foundation: 'Foundation',
      transformation: 'Transformation',
      scale_up: 'Scale-up',
      diversification: 'Diversification',
    } as Record<string, string>,
    sheet: {
      objective: 'Objective',
      rationale: 'Rationale',
      impact: 'Impact',
      investment: 'Investment',
      complexity: 'Complexity',
      timeline: 'Timeline',
      owner: 'Owner',
      milestones: 'Milestones',
      dependencies: 'Dependencies',
      risks: 'Risks',
      kpis: 'KPIs',
      status: 'Status in this scenario',
      none: 'None',
      revenue: 'Revenue at run rate',
      ebitda: 'EBITDA at run rate',
      headcount: 'Headcount',
      capacity: 'Capacity added',
      startYear: 'Start',
      rampComplete: 'Ramp complete',
      earliest: 'Earliest start',
      ramp: 'Ramp',
      years: 'years',
      close: 'Close',
    },
    complexity: { low: 'Low', medium: 'Medium', high: 'High' } as Record<string, string>,
  },
  direction: {
    reveal: 'The strata',
    revealLead:
      'Assumptions, initiatives, plan. Hover a lever or a chip to see what moves with it.',
    bands: { assumptions: 'Assumptions', initiatives: 'Initiatives', plan: 'Plan' },
    bandIndex: { assumptions: '01', initiatives: '02', plan: '03' },
    lines: {
      revenue: 'Revenue',
      ebitda: 'EBITDA',
      capex: 'Capex',
      fcf: 'Free cash flow',
      cumulativeFcf: 'Cumulative FCF',
    } as Record<string, string>,
    idle: 'Nothing lit. Move over a lever in the rail.',
    lit: (n: number, m: number, k: number) =>
      `${n} assumptions, ${m} initiatives, ${k} plan lines move.`,
    matrix: 'Where to play',
    matrixLead: 'Attractiveness against competitive position. Bubble size is 2031 revenue.',
    axisX: 'Competitive position',
    axisY: 'Market attractiveness',
    quadrants: {
      grow: 'Grow',
      improve: 'Improve',
      maintain: 'Maintain or harvest',
      exit: 'Exit or restructure',
    },
    table: 'Classification',
    tableLead: 'Each product market, its category, and the reason.',
    cols: {
      cell: 'Product market',
      category: 'Category',
      rationale: 'Rationale',
      delta: 'vs Base',
    },
    unchanged: 'Same as Base',
    categories: {
      grow: 'Grow',
      maintain: 'Maintain',
      improve: 'Improve',
      restructure: 'Restructure',
      harvest: 'Harvest',
      exit: 'Exit',
    } as Record<string, string>,
    cellShort: {
      steel: 'Steel',
      construction: 'Construction',
      glass: 'Glass',
      water: 'Water',
      chemicals: 'Chemicals',
      agriculture: 'Agriculture',
      bricks_mkt: 'Bricks',
      export_gcc: 'Export GCC',
      export_extended: 'Export EA/SA',
    } as Record<string, string>,
  },
  common: {
    illustrativeFootnote:
      'Illustrative. The engagement delivers a formula-driven Excel model (RFQ 3.1); this view mirrors its output.',
  },
} as const

export type ViewId = keyof typeof strings.views
