// All UI copy lives here so an Arabic pass can be done in one file.
// Rules from the brief: no em dashes, no "AI", "Sia" never "Sia Partners".

export const strings = {
  app: {
    name: 'STRATA',
    tagline: 'Dynamic strategy cockpit',
    client: 'Saudi Lime Industries Company, 2027 to 2031',
    illustrative: 'Illustrative data',
    illustrativeLong: 'Illustrative data. Invented for this proof of concept, not SLIC actuals.',
    scenario: 'Scenario',
    reset: 'Reset to base',
    builtBy: 'A Sia proof of concept',
  },
  rail: {
    levers: 'Levers',
    presets: 'Scenario presets',
    explain: 'Explain this result',
    explainHint: 'Show the rules and assumptions behind every number.',
    moves: 'Moves',
    custom: 'Custom',
  },
  scenarios: {
    base: 'Base',
    growth: 'Growth',
    upside: 'Upside',
    downside: 'Downside',
    custom: 'Custom',
  } as Record<string, string>,
  levers: {
    L1: {
      options: { delayed: 'Delayed', onPlan: 'On plan', accelerated: 'Accelerated' },
      fine: 'Giga-project phasing',
      unit: 'x base growth',
    },
    L2: { unit: 'index, base 100' },
    L3: { unit: 'SAR m over 5 years' },
    L4: {
      options: { organic: 'Organic', selective: 'Selective', aggressive: 'Aggressive' },
      long: { organic: 'Organic only', selective: 'Selective inorganic', aggressive: 'Aggressive' },
    },
    L5: {
      options: { domestic: 'Domestic', gcc: 'GCC', extended: 'Extended' },
      long: { domestic: 'Domestic only', gcc: 'GCC', extended: 'GCC + East Africa and South Asia' },
    },
    L6: {
      options: { none: 'None', voluntary: 'Voluntary', regulated: 'Regulated' },
      unit: 'SAR per tCO2',
    },
    short: {
      L1: 'demand',
      L2: 'energy index',
      L3: 'envelope',
      L4: 'risk appetite',
      L5: 'export ambition',
      L6: 'carbon cost',
    } as Record<string, string>,
  },
  assumptionKeys: {
    demand: 'Demand',
    utilization: 'Utilization',
    priceIndex: 'Price index',
    costPerTon: 'Cost per ton',
    ebitda: 'EBITDA',
    portfolio: 'Portfolio',
    capex: 'Capex',
    roadmap: 'Roadmap',
    sites: 'Sites',
    classification: 'Classification',
  } as Record<string, string>,
  views: {
    direction: {
      tab: 'Strategic direction',
      title: 'Strategic direction',
      lead: 'Where to play, how each product market is classified, and which layers of the plan move when a lever moves.',
    },
    portfolio: {
      tab: 'Growth portfolio',
      title: 'Growth portfolio',
      lead: 'Every initiative, funded or deferred or out, with the lever value that would change its status.',
    },
    financials: {
      tab: 'Financial plan',
      title: 'Financial plan',
      lead: 'Revenue, EBITDA, capex and free cash flow for 2027 to 2031 against the base case.',
    },
    operations: {
      tab: 'Operations and people',
      title: 'Operations and people',
      lead: 'Site capacity and utilization, capex phasing, headcount and Saudization under the current scenario.',
    },
    roadmap: {
      tab: 'Roadmap',
      title: 'Roadmap',
      lead: 'Selected initiatives on a 2027 to 2031 timeline in the five plan layers, with dependencies.',
    },
    tracker: {
      tab: 'Tracker',
      title: 'Tracker',
      lead: 'Plan assumptions against actuals, and the decisions that become due when they diverge.',
    },
  },
  financials: {
    kpi: {
      revenue2031: '2031 revenue',
      margin2031: '2031 EBITDA margin',
      cumCapex: 'Cumulative capex',
      cumFcf: 'Cumulative free cash flow',
    },
    units: { sarm: 'SAR m', pct: '%', plan: '2027 to 2031' },
    vsBase: 'vs Base',
    mainChart: 'Revenue and EBITDA',
    mainChartLead: '2026 actual, then the plan. Dashed lines are the Base case.',
    secondChart: 'Capex and free cash flow',
    secondChartLead:
      'Capex stacked as base business and initiatives. Free cash flow after working capital.',
    legend: {
      revenue: 'Revenue',
      ebitda: 'EBITDA',
      baseRevenue: 'Base revenue',
      baseEbitda: 'Base EBITDA',
      capexBase: 'Base capex',
      capexInitiatives: 'Initiative capex',
      fcf: 'Free cash flow',
    },
    strip: 'Scenario compare',
    stripLead: 'The four cases the plan must hold, and where the current levers sit.',
    stripCols: {
      scenario: 'Scenario',
      revenue: 'Revenue 2031',
      ebitda: 'EBITDA 2031',
      fcf: 'Cumulative FCF',
    },
  },
  portfolio: {
    columns: { in: 'In plan', deferred: 'Deferred', out: 'Out' },
    columnLead: {
      in: 'Funded within the envelope.',
      deferred: 'Viable, waiting on capital, returns or a dependency.',
      out: 'Fails a strategic rule at these lever values.',
    },
    strip: {
      envelope: 'Capital envelope',
      committed: 'Committed',
      headroom: 'Headroom',
      counts: 'Initiatives',
      diversification: '2031 revenue from new products and markets',
    },
    card: {
      capex: 'Capex',
      npv: 'NPV',
      ebitda: 'EBITDA',
      owner: 'Owner',
      dependsOn: 'Depends on',
      start: 'Start',
    },
    reason: {
      capital: 'Envelope exhausted',
      returns: 'NPV below zero at the hurdle rate',
      dependency: 'Waits for a dependency',
    },
    trigger: {
      becomesViable: 'Becomes viable if',
      fundedOnce: 'Funded once',
      staysIn: 'Stays in while',
      dropsOut: 'Drops out if',
      more: 'more',
      noBoundary: 'No lever value changes this.',
    },
    layers: {
      quick_wins: 'Quick wins',
      foundation: 'Foundation',
      transformation: 'Transformation',
      scale_up: 'Scale-up',
      diversification: 'Diversification',
    } as Record<string, string>,
    sheet: {
      objective: 'Objective',
      rationale: 'Rationale',
      impact: 'Impact',
      investment: 'Investment',
      complexity: 'Complexity',
      timeline: 'Timeline',
      owner: 'Owner',
      milestones: 'Milestones',
      dependencies: 'Dependencies',
      risks: 'Risks',
      kpis: 'KPIs',
      status: 'Status in this scenario',
      none: 'None',
      revenue: 'Revenue at run rate',
      ebitda: 'EBITDA at run rate',
      headcount: 'Headcount',
      capacity: 'Capacity added',
      startYear: 'Start',
      rampComplete: 'Ramp complete',
      earliest: 'Earliest start',
      ramp: 'Ramp',
      years: 'years',
      close: 'Close',
    },
    complexity: { low: 'Low', medium: 'Medium', high: 'High' } as Record<string, string>,
  },
  direction: {
    reveal: 'The strata',
    revealLead:
      'Assumptions, initiatives, plan. Hover a lever or a chip to see what moves with it.',
    bands: { assumptions: 'Assumptions', initiatives: 'Initiatives', plan: 'Plan' },
    bandIndex: { assumptions: '01', initiatives: '02', plan: '03' },
    lines: {
      revenue: 'Revenue',
      ebitda: 'EBITDA',
      capex: 'Capex',
      fcf: 'Free cash flow',
      cumulativeFcf: 'Cumulative FCF',
    } as Record<string, string>,
    idle: 'Nothing lit. Move over a lever in the rail.',
    lit: (n: number, m: number, k: number) =>
      `${n} assumptions, ${m} initiatives, ${k} plan lines move.`,
    matrix: 'Where to play',
    matrixLead: 'Attractiveness against competitive position. Bubble size is 2031 revenue.',
    axisX: 'Competitive position',
    axisY: 'Market attractiveness',
    quadrants: {
      grow: 'Grow',
      improve: 'Improve',
      maintain: 'Maintain or harvest',
      exit: 'Exit or restructure',
    },
    table: 'Classification',
    tableLead: 'Each product market, its category, and the reason.',
    cols: {
      cell: 'Product market',
      category: 'Category',
      rationale: 'Rationale',
      delta: 'vs Base',
    },
    unchanged: 'Same as Base',
    categories: {
      grow: 'Grow',
      maintain: 'Maintain',
      improve: 'Improve',
      restructure: 'Restructure',
      harvest: 'Harvest',
      exit: 'Exit',
    } as Record<string, string>,
    cellShort: {
      steel: 'Steel',
      construction: 'Construction',
      glass: 'Glass',
      water: 'Water',
      chemicals: 'Chemicals',
      agriculture: 'Agriculture',
      bricks_mkt: 'Bricks',
      export_gcc: 'Export GCC',
      export_extended: 'Export EA/SA',
    } as Record<string, string>,
  },
  operations: {
    year: 'Year',
    scrubberHint: 'Applies to every panel on this view.',
    sites: 'Sites',
    capacity: 'Capacity',
    utilization: 'Utilization',
    capexPhasing: 'Capex phasing',
    touching: 'Initiatives at this site',
    noneTouching: 'No selected initiative at this site.',
    kt: 'kt',
    saturated: 'At capacity, demand is being lost',
    people: 'People',
    headcount: 'Headcount',
    saudization: 'Saudization',
    nitaqat: 'Nitaqat target',
    costPerTon: 'Cost per ton, all in',
    workforce: 'Workforce initiative',
    supply: 'Supply chain',
    energy: 'Energy cost per ton of lime',
    carbon: 'Carbon cost per ton of lime',
    logistics: 'Export logistics per ton',
    under: 'under',
    sarPerTon: 'SAR per ton',
    people_lead:
      'Headcount follows tonnage plus the selected initiatives. Saudization moves with the workforce program.',
    supply_lead: 'Unit costs the levers set directly.',
  },
  roadmap: {
    lead: 'Quarters 2027 to 2031. Solid bars are funded; ghost bars are viable but waiting on capital.',
    needs: (x: string) => `needs SAR ${x}m more`,
    critical: 'Critical path',
    milestone: 'Ramp complete',
    dependency: 'Dependency',
    ghost: 'Deferred, capital',
    funded: 'Funded',
    empty: 'No initiative in this layer at these lever values.',
    quarters: ['Q1', 'Q2', 'Q3', 'Q4'],
  },
  tracker: {
    lead: (year: number) => `Type what actually happened in ${year}. The plan re-decides itself.`,
    cols: {
      lever: 'Lever',
      plan: 'Plan assumption',
      actual: (year: number) => `Actual ${year}`,
      status: 'Status',
    },
    notTracked: 'Not tracked in this proof of concept',
    awaiting: 'Awaiting actual',
    onPlan: 'On plan',
    above: 'Above plan',
    below: 'Below plan',
    clear: 'Clear actuals',
    fired: 'Triggers fired',
    firedLead:
      'Initiatives whose status changes once the actuals are in, and the decision now due.',
    none: 'No trigger fired. The plan holds at these actuals.',
    decision: 'Decision due',
    decisions: {
      out: 'Stop or re-scope. The strategic condition no longer holds.',
      deferred: 'Hold. Viable, but the envelope or the returns no longer cover it.',
      in: 'Approve. The condition is now met and capital is available.',
    } as Record<string, string>,
    chart: 'Plan against tracked plan',
    chartLead: 'Solid lines carry the actuals; dashed lines are the plan as approved.',
    legend: {
      revenue: 'Revenue, tracked',
      ebitda: 'EBITDA, tracked',
      planRevenue: 'Revenue, plan',
      planEbitda: 'EBITDA, plan',
    },
    inputHint: { L1multiplier: '0.7 to 1.3', L2: '80 to 160', L6: '0, 40 or 120' } as Record<
      string,
      string
    >,
    ownership: 'This is what SLIC owns after handover: the same rules, run on real numbers.',
  },
  cover: {
    tagline: 'A plan that re-decides itself',
    enter: 'Enter',
    walkthrough: 'Play the walkthrough',
    walkthroughHint:
      'Eleven chapters, about four minutes, with voice. What it is and how it works.',
    poweredBy: 'Powered by',
    home: 'Back to the cover',
  },
  walkthrough: {
    stop: 'Stop',
    next: 'Next chapter',
    step: 'Chapter',
    of: 'of',
    done: 'Walkthrough complete. The levers are yours.',
    titles: [
      'What it is',
      'The six levers',
      'The engine',
      'Financial plan',
      'Growth portfolio',
      'Strategic direction',
      'Operations and people',
      'Roadmap',
      'Tracker',
      'Explain this result',
      'Close',
    ],
    captions: [
      'STRATA is a dynamic strategy cockpit, built by Sia for Saudi Lime Industries and its 2027 to 2031 strategic business plan. Most strategy plans are documents, fixed on the day they are printed. STRATA is a system. The plan is computed live from six levers, and every number on screen can be traced back to the lever and the rule that produced it. All data here is illustrative.',
      'On the left are the six levers the Board controls: domestic demand outlook, energy cost, capital envelope, risk appetite, export ambition and carbon cost. Each card shows the current value, what it moves, and the assumptions it touches. Four presets, Base, Growth, Upside and Downside, set all six at once. Move any lever and the whole plan recomputes in a few milliseconds.',
      'Behind the screen is a ten-step engine. It builds demand by sector, checks it against site capacity, moves prices with utilization, and builds cost per ton from energy and carbon. It then tests every initiative against its rules, selects a portfolio within the capital envelope, and consolidates everything into a five-year P and L, a classification of every market, and a roadmap. The engine is plain code with no license to buy, and every number lives in two data files a consultant can edit.',
      'The Financial plan view is the first thing a CFO wants to see. Four headline numbers for 2031, revenue and EBITDA against the Base case as dashed lines, capex and free cash flow by year, and the four presets side by side. When a lever moves, the numbers count to their new values, and delta chips show the change against Base: teal when favourable, coral when not.',
      'The Growth portfolio holds sixteen initiatives in three columns: in plan, deferred, and out. Every card shows capex, NPV, EBITDA, the owner, and a trigger point: the lever value that would change its status. A capital bar shows what the envelope funds. Click a card for the full initiative sheet: objective, rationale, impact, timeline, risks and KPIs.',
      'Strategic direction is the argument of the whole product. Three layers: assumptions, initiatives, plan. Hover a lever and the layers light up top to bottom, showing which assumptions it touches, which initiatives those affect, and which plan lines change. Below, a where-to-play matrix places every product market by attractiveness and position, and a table gives each one its category and the reason.',
      'Operations and people shows the three sites, Riyadh, Al Kharj and Jeddah, with a utilization gauge, capacity, capex phasing and the initiatives at each site, for any year on the scrubber. Below it, headcount, Saudization against the Nitaqat target, cost per ton, and the unit costs the levers set directly.',
      'The Roadmap lays the funded initiatives on a quarterly timeline in the five layers of the plan, from quick wins to diversification. Ghost bars show viable initiatives waiting on capital and how much more envelope they need. Dependencies are drawn between bars, milestones mark ramp completion, and the critical path is in teal.',
      'The Tracker is what SLIC owns after handover. Type the actual for an elapsed year and the engine re-runs with it in place. The triggers-fired panel lists the initiatives whose status changes and the decision now due. The same rules, run on real numbers.',
      'Every number can explain itself. Switch on Explain this result and a small slash appears beside every KPI, card and site. Click it for the rules and assumptions behind that value, with the lever values applied. Traceable in two clicks, as the RFQ asks.',
      'That is STRATA. Six levers, one engine, six views, and every number traceable. Move a lever and the plan re-settles. Illustrative data throughout: the numbers change when the data does. Powered by Sia.',
    ],
  },

  explain: {
    title: 'Why this number',
    lead: 'The rules and assumptions behind it, with the lever values applied.',
    rule: 'Rule',
    assumption: 'Assumption',
    lever: 'Lever',
    value: 'Value',
    icon: 'Explain',
    none: 'No trace recorded for this value.',
    rules: {
      'demand.compound': 'Demand compounds sector growth times the demand multiplier',
      'demand.gigaPhasing': 'Giga-project phasing scaled by sector sensitivity',
      'demand.export': 'Export volumes from the ambition level',
      'demand.export.requires': 'Export level needs an initiative',
      'capacity.sum': 'Site capacity summed by product family',
      'capacity.addition': 'Capacity added by a selected initiative',
      'capacity.calibration': 'Sales calibrated to base utilization',
      'price.elasticity': 'Price index moves with utilization',
      'price.clamp': 'Price index clamped',
      'price.list': 'List price blended by capacity',
      'price.export': 'Export price at a discount to domestic',
      'cost.base': 'Base cost per ton',
      'cost.energy': 'Energy share scaled by the energy index',
      'cost.carbon': 'Carbon cost on process emissions',
      'cost.exportLogistics': 'Export logistics per ton',
      'calibration.price': 'Price calibrated to 2026 revenue',
      'calibration.cost': 'Cost calibrated to 2026 EBITDA',
      'revenue.volumeTimesPrice': 'Revenue is volume times price',
      'ebitda.revenueMinusCost': 'EBITDA is revenue minus cost',
      'consolidate.revenue': 'Base business plus initiatives',
      'consolidate.ebitda': 'Base business plus initiatives',
      'consolidate.capex': 'Maintenance capex plus initiative capex',
      'consolidate.fcf': 'EBITDA minus capex minus working capital',
      'consolidate.margin': 'EBITDA divided by revenue',
      'consolidate.cumulativeFcf': 'Sum of plan-year free cash flow',
      'people.headcount': 'Headcount follows tonnage plus initiatives',
      'people.saudization': 'Saudization moves with the workforce program',
      'people.costPerTon': 'All-in cost per ton, indexed',
      'portfolio.status': 'Status in this scenario',
      'portfolio.npv': 'NPV at the plan discount rate',
      'portfolio.envelope': 'Capital envelope',
      'portfolio.committed': 'Capital committed',
      'portfolio.ebitdaScale': 'EBITDA scales with a lever',
      'viability.rule': 'Strategic rule',
      'classify.attractiveness': 'Attractiveness score input',
      'classify.position': 'Position score input',
      'classify.category': 'Category by threshold',
      'roadmap.start': 'Earliest start',
      'roadmap.ramp': 'Ramp years',
      'roadmap.status': 'Funded within the envelope',
      'roadmap.dependency': 'Waits for a dependency',
      'sites.capacity': 'Site capacity',
      'sites.utilization': 'Site utilization',
      'sites.initiatives': 'Initiatives at the site',
      'diversification.share': 'Revenue from new products and markets',
    } as Record<string, string>,
  },
  common: {
    illustrativeFootnote:
      'Illustrative. The engagement delivers a formula-driven Excel model (RFQ 3.1); this view mirrors its output.',
  },
} as const

export type ViewId = keyof typeof strings.views
